# Week 3 Labs, Rank 1 ndarrays

In [2]:
import numpy as np
an_array = np.array([3, 33, 333]) #create a rank 1 array
print(type(an_array)) #printing the type of the array

<class 'numpy.ndarray'>


In [3]:
#test the shape of the array
print(an_array.shape)

(3,)


In [4]:
print(an_array[0], an_array[1], an_array[2]) #test the indexes

3 33 333


In [5]:
an_array[0] = 888 #to replace the first element

print(an_array)

[888  33 333]


# Move on to two-dimensional arrays

In [6]:
another = np.array([[11,12,13],[21,22,23]]) #to create a rank 2 array
print(another) #to print the array
print("The shape is 2 rows, 3 columns:", another.shape)
print("accessing elements[0,0], [0,1] and[1,0] of the ndarray", another)
                    

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns: (2, 3)
accessing elements[0,0], [0,1] and[1,0] of the ndarray [[11 12 13]
 [21 22 23]]


In [7]:
#create a 2x2 array of zeros
ex1 = np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [8]:
#create a 2x2 array filled of 9.0
ex2 = np.full((2,2), 9.0)
print(ex2)

[[9. 9.]
 [9. 9.]]


In [9]:
#create a matrix with the diagonal 1s and the other 0
ex3 = np.eye(2,2)
print(ex3)

[[1. 0.]
 [0. 1.]]


In [10]:
#create an array of 1s
ex4 = np.ones((1,2))
print(ex4)

[[1. 1.]]


In [11]:
#the ndarray (ex4) is a 2D array with one row and two column
print(ex4.shape)

#we need 2 indexes to access one element
print()
print(ex4[0,1])


(1, 2)

1.0


In [12]:
#create an array of random floats between o and 1
ex5 = np.random.random((2,2))
print(ex5)

[[0.22875692 0.25680677]
 [0.27473938 0.80696737]]


### Numpy array indexes

In [13]:
# rank 2 array of shape (3,4)
an_array = np.array([[11,12,13,14],[21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


### Use array slicing to get a subarray consisting of the first 2 rows x 2 columns

In [14]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


 When you modify a slice, you actually modify the underliying array

In [15]:
print("Before:",an_array[0, 1]) # inspect the element at 0, 1
a_slice[0,0] = 1000 # a-slice[0,0] is the same piece of data as an_array[0,1]
print("After:",an_array[0, 1])

Before: 12
After: 1000


# Use both Integer Indexes and slicing indexing

We can use combinations integer indexing and slicing indexing to create different shaped matrices.

In [16]:
#create a rank 2 array of shape (2,4)
an_array = np.array([[11,12,13,14],[21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [17]:
#using both integer indexing and and slicing indexing generates an array of lower rank
row_rank1 = an_array[1, :] #Rank 1 view
print(row_rank1, row_rank1.shape) # 1 single []



[21 22 23 24] (4,)


In [18]:
#slicing alone: generates an array of the same rank as an_array
row_rank2 = an_array[1:2, :] #Rank 2 view
print(row_rank2, row_rank2.shape) # the double braket reflects the 2D array

[[21 22 23 24]] (1, 4)


In [19]:
# We can do the same thing for column of an array
print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]
print(col_rank1, col_rank1.shape) # Rank 1
print()
print(col_rank2, col_rank2.shape) # Rank 2
print()



[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)



###### Array indexing for changing elements

Sometimes it's useful to use an array of indexes to acces or change elements

In [20]:
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])
print('Original Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [21]:
# Create an array of indices
col_indices = np.array([0,1,2,0])
print('\nCol indices picked:', col_indices)

row_indices = np.arange(4)
print('\nRow indices picked:', row_indices)



Col indices picked: [0 1 2 0]

Row indices picked: [0 1 2 3]


In [22]:
# Examine the pairing of row_indices and column_indices
for row,col in zip(row_indices, col_indices):
    print(row, ", ",col)

0 ,  0
1 ,  1
2 ,  2
3 ,  0


In [23]:
# Select one element from each row
print('Values in the array at those indices:',an_array[row_indices, col_indices])

Values in the array at those indices: [11 22 33 41]


In [24]:
# Change one element form each row using the indices selected
an_array[row_indices, col_indices] += 100000
print('\nChanged Array:')
print(an_array)


Changed Array:
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


# Bolean Indexing

## Array Indexing for changing element

In [40]:
# Create a 3x2 array
an_array = np.array([[11,12], [21,22], [31,32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [41]:
# Create a filter which will be boolean for whether each element meets this criteria
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

Notice that the filter is the same size as an_array filled with True for elements that meet the criteria and False for others.

In [42]:
# Select the elements that meet that criteria
print(an_array[filter])

[21 22 31 32]


In [47]:
# For short, do the following
an_array[an_array > 15]

array([112,  21, 122,  31, 132])

In [44]:
# Find the values between 20 and 30
an_array[(an_array > 20) & (an_array<30)]

array([21, 22])

In [46]:
# Find all the even values
an_array[an_array %2 ==0]

array([112, 122, 132])

In [45]:
# Change element in the array applying a similar logical filter
# Add 100 to all even values
an_array[an_array %2 == 0] +=100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


# Numpy: ndarray Data Types and Operations

### Data Types

In [48]:
# Python assigns the data type
ex1 = np.array([11,12])
print(ex1.dtype)

int64


In [49]:
ex2 = np.array([11.0, 12.0])
print(ex2.dtype)

float64


In [50]:
# Tell Python the data type you want
ex3 = np.array([11,21], dtype = np.int64)
print(ex3.dtype)

int64


In [51]:
# Force float into integers using the floor function
ex4 = np.array([11.1, 12.7], dtype = np.int64)
print(ex4.dtype)
print()
print(ex4)


int64

[11 12]


In [52]:
# Force integers into floats if you anticipate the values may change to float later
ex5 = np.array([11,21], dtype = np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


### Arithmetic Array Operations

In [56]:
x = np.array([[111,112], [121,122]], dtype = np.int64)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype = np.float64)
print(x)
print()
print(y)                        

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [57]:
# Add X to Y using the plus sign
print(x+y)
print()

[[322.1 324.1]
 [342.1 344.1]]



In [58]:
# Add X to Y using the function ADD
print(np.add(x,y))


[[322.1 324.1]
 [342.1 344.1]]


In [59]:
# Subtract X from Y using the minus sign
print(x-y)
print()

[[-100.1 -100.1]
 [-100.1 -100.1]]



In [61]:
# Subtract X from Y using the function SUBSTRACT
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [62]:
# Multiply X by Y using the multiplication sign
print(x*y)
print()
print(np.multiply(x,y)) # Using the multiply function 

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [63]:
# Divide X by Y using the division sign
print(x/y)
print()
print(np.divide(x,y)) # Using the DIVIde function

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [65]:
# Square root
print(np.sqrt(x))
print()

[[10.53565375 10.58300524]
 [11.         11.04536102]]



In [66]:
# Exponent (e**x)
print(np.exp(x))
print()



[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]



# Speed Test: ndarray vs. list

First set up the parameters for the speed test. We will be testing time to sum elements in an ndarray vs list

In [9]:
from numpy import arange
from timeit import Timer
size = 1000000
timeit = 1000

In [10]:
# Create ndarray with values 0, 1, 2, 3,..., size-1
ndarray = arange(size)
print(type(ndarray))

<class 'numpy.ndarray'>


In [12]:
# Timer expects the operations as a parameter
# Here we pass ndarray.sum()
timer_numpy = Timer("ndarray.sum", "from_main_import nd_array" )
print("Time taken by numpy ndarray: %f seconds" %
     (timer_numpy.timeit(timeits/timeits))

SyntaxError: unexpected EOF while parsing (<ipython-input-12-429eefb480fb>, line 5)